checkpoint ... complete fullTestRun ...

diff --git a/bin/fullTestRun b/bin/fullTestRun
--- a/bin/fullTestRun
+++ b/bin/fullTestRun
@@ -1,4 +1,4 @@
-set -e
+set -exv
 . defStone.env
 
 #	createStone -g battery_3215 3.2.15
@@ -7,38 +7,38 @@ set -e
 
 for gsVersion in 3215 339 343 ; do
 	# all installs are done as DataCurator
-	for stone_type in GLASS GLASS1 GsDevKit TODE ; do
-		./install${stone_type} $gsVersion
-		./upgradeImage $stone_type $gsVersion
-		./upgradeSeasideImage $stone_type $gsVersion
-		./upgradeGsDevKitImage $stone_type $gsVersion
-	done
-	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade.topaz"
+#	for stone_type in GLASS GLASS1 GsDevKit TODE ; do
+#		./install${stone_type} $gsVersion
+#		./upgradeImage $stone_type $gsVersion
+#		./upgradeSeasideImage $stone_type $gsVersion
+#		./upgradeGsDevKitImage $stone_type $gsVersion
+#	done
+	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_datacurator_upgrade.topaz"
 	if [ "$gsVersion" = "3215" ] ; then
-		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade_3215.topaz"
+		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_datacurator_upgrade_3215.topaz"
 	fi
-	for stone_type in GLASS1 GsDevKit ; do
+	for stone_type in GLASS1 ; do # GsDevKit ; do
 		./installSeaside33 ${stone_type} $gsVersion DataCurator
-		./upgradeImage datacurator_${stone_type} ${gsVersion}
-		./upgradeSeasideImage datacurator_${stone_type} ${gsVersion} DataCurator $upgradeDriver
+		./upgradeImage DataCurator_${stone_type} ${gsVersion}
+		./upgradeSeasideImage DataCurator_${stone_type} ${gsVersion} DataCurator $upgradeDriver
 	done
 done
 
-for gsVersion in 3215 339 343 ; do
-	# the seaside tests install seaside as a non-Datacurator user (seaside)
-	# DON'T run tests (for now - need to have seaside stones) but want to make
-	# 	sure that upgrades work
-	
-	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade.topaz"
-	if [ "$gsVersion" = "3215" ] ; then
-		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade_3215.topaz"
-	fi
-	for stone_type in GLASS1 GsDevKit ; do
-		./installSeaside33 ${stone_type} $gsVersion
-		./upgradeImage seaside_${stone_type} ${gsVersion}
-		./upgradeSeasideImage seaside_${stone_type} ${gsVersion} seaside $upgradeDriver
-	done
-done
+#for gsVersion in 3215 339 343 ; do
+#	# the seaside tests install seaside as a non-DatacCrator user (seaside)
+#	# DON'T run tests (for now - need to have seaside stones) but want to make
+#	# 	sure that upgrades work
+#	
+#	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade.topaz"
+#	if [ "$gsVersion" = "3215" ] ; then
+#		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade_3215.topaz"
+#	fi
+#	for stone_type in GLASS1 GsDevKit ; do
+#		./installSeaside33 ${stone_type} $gsVersion
+#		./upgradeImage seaside_${stone_type} ${gsVersion}
+#		./upgradeSeasideImage seaside_${stone_type} ${gsVersion} seaside $upgradeDriver
+#	done
+#done
 
 set +e
 
@@ -51,36 +51,55 @@ touch ${upgradeLogDir}TEST_RESULTS
 
 finalStatus=0
 for gsVersion in 3215 339 343 ; do
-	for stone_type in GLASS GLASS1 GsDevKit TODE ; do
-		newExtent -s snapshots/extent0_preparedSeasideImage_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
-		./runImageTests ${stone_type} ${gsVersion}
+#	for stone_type in GLASS GLASS1 GsDevKit TODE ; do
+#		newExtent -s snapshots/extent0_preparedSeasideImage_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
+#		./runImageTests ${stone_type} ${gsVersion}
+#		exitStatus="$?"
+#		if [ $exitStatus -ne 0 ] ; then
+#			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
+#--->failed runImageTests for ${stone_type}_${gsVersion}
+#EOF
+#			finalStatus=1
+#		else
+#			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
+#passed runImageTests for ${stone_type}_${gsVersion}
+#EOF
+#		fi
+#	done
+
+	for stone_type in GLASS1 ; do # GsDevKit ; do
+		# seaside build for DataCurator user
+		newExtent -s snapshots/extent0_preparedSeasideImage_DataCurator_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
+		./runImageTests DataCurator_${stone_type} ${gsVersion} DataCurator
 		exitStatus="$?"
 		if [ $exitStatus -ne 0 ] ; then
 			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
---->failed runImageTests for ${stone_type}_${gsVersion}
+--->failed runImageTests for DataCurator_${stone_type}_${gsVersion}
 EOF
 			finalStatus=1
 		else
 			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
-passed runImageTests for ${stone_type}_${gsVersion}
+passed runImageTests for DataCurator_${stone_type}_${gsVersion}
 EOF
 		fi
 	done
-	for stone_type in GLASS1 GsDevKit ; do
-		newExtent -s snapshots/extent0_preparedSeasideImage_seaside_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
-		./runImageTests seaside_${stone_type} ${gsVersion} seaside
-		exitStatus="$?"
-		if [ $exitStatus -ne 0 ] ; then
-			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
---->failed runImageTests for seaside_${stone_type}_${gsVersion}
-EOF
-			finalStatus=1
-		else
-			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
-passed runImageTests for seaside_${stone_type}_${gsVersion}
-EOF
-		fi
-	done
+
+#	for stone_type in GLASS1 GsDevKit ; do
+#		# seaside build for seaside user
+#		newExtent -s snapshots/extent0_preparedSeasideImage_seaside_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
+#		./runImageTests seaside_${stone_type} ${gsVersion} seaside
+#		exitStatus="$?"
+#		if [ $exitStatus -ne 0 ] ; then
+#			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
+#--->failed runImageTests for seaside_${stone_type}_${gsVersion}
+#EOF
+#			finalStatus=1
+#		else
+#			cat - >> ${upgradeLogDir}/TEST_RESULTS << EOF
+#passed runImageTests for seaside_${stone_type}_${gsVersion}
+#EOF
+#		fi
+#	done
 done
 
 
