checkpoint ... added runImageTests for use in fullTestRun ... debugged, but not run

diff --git a/bin/fullTestRun b/bin/fullTestRun
--- a/bin/fullTestRun
+++ b/bin/fullTestRun
@@ -1,4 +1,5 @@
 set -e
+. defStone.env
 
 #	createStone -g battery_3215 3.2.15
 #	createStone -g battery_339 3.3.9
@@ -13,26 +14,48 @@ set -e
 #		./upgradeGsDevKitImage $stone_type $gsVersion
 #	done
 #done
+#
+#for gsVersion in 3215 339 343 ; do
+#	# the seaside tests install seaside as a non-Datacurator user (seaside)
+#	
+#	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade.topaz"
+#	if [ "$gsVersion" = "3215" ] ; then
+#		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade_3215.topaz"
+#	fi
+#	for stone_type in GLASS1 GsDevKit ; do
+#		./installSeaside33 ${stone_type} $gsVersion
+#		./upgradeImage seaside_${stone_type} ${gsVersion}
+#		./upgradeSeasideImage seaside_${stone_type} ${gsVersion} seaside $upgradeDriver
+#	done
+#done
 
+set +e
+
+pushd "${upgradeLogDir}" >& /dev/null
+	rm -rf *.log *.out *.topaz *.conf
+popd
+
+finalStatus=0
 for gsVersion in 3215 339 343 ; do
-	# the seaside tests install seaside as a non-Datacurator user (seaside)
-	
-	upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade.topaz"
-	if [ "$gsVersion" = "3215" ] ; then
-		upgradeDriver="$GS_HOME/shared/repos/GsDevKit_upgrade/bin/seaside3_upgrade_3215.topaz"
-	fi
+	for stone_type in GLASS ; do # GLASS1 GsDevKit TODE ; do
+		newExtent -s snapshots/extent0_preparedSeasideImage_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
+		./runImageTests ${stone_type} ${gsVersion}
+		exitStatus="$?"
+		if [ $exitStatus -ne 0 ] ; then
+			echo "failed runImageTests for ${stone_type}_${gsVersion}"
+			finalStatus=1
+		fi
+	done
 	for stone_type in GLASS1 GsDevKit ; do
-		./installSeaside33 ${stone_type} $gsVersion
-		./upgradeImage seaside_${stone_type} ${gsVersion}
-		./upgradeSeasideImage seaside_${stone_type} ${gsVersion} seaside $upgradeDriver
+		newExtent -s snapshots/extent0_preparedSeasideImage_seaside_${stone_type}_${gsVersion}.dbf $GEMSTONE_NAME
+		./runImageTests seaside_${stone_type} ${gsVersion} seaside
+		exitStatus="$?"
+		if [ $exitStatus -ne 0 ] ; then
+			echo "failed runSeasideImageTests for ${stone_type}_${gsVersion}"
+			finalStatus=1
+		fi
 	done
 done
 
-for gsVersion in 3215 339 343 ; do
-	for stone_type in GLASS GLASS1 GsDevKit TODE ; do
-		./runImageTests $gsVersion
-	done
-	for stone_type in GLASS GLASS1 GsDevKit ; do
-		./runSeasideImageTests ${gsVersion}
-	done
-done
+
+exit $finalStatus
